### ISSUE TITLE
Incompatibility with HitScoreVisualizer

### ISSUE THREAD

**Issue by Loloppe** [rynan4818/PlayerInfoViewer#1]
Issue: My HitScoreVisualizer usually show text (numbers), but after installing this plugin, it now show specific symbol.
Turning on Bloom seem to fix the issue temporary.

HitScoreVisualizer: https://github.com/ErisApps/HitScoreVisualizer

Without bloom (issue):
![image](https://user-images.githubusercontent.com/54846763/189553010-4226384d-7671-4c44-a878-ffa7a36dd0ac.png)<
With bloom (work fine):
![image](https://user-images.githubusercontent.com/54846763/189553158-d36cdd59-6211-43d0-9c02-7af3221c37ac.png)

**Comment by rynan4818** [comment]
PlayerInfoViewer, but given the way the program works, there is no part of it that runs during gameplay.
I can't think of any cause that would affect the display of HitScoreVisualizer.
Perhaps PlayerInfoViewer has nothing to do with it.

https://user-images.githubusercontent.com/14249877/189636340-40901060-6260-4daf-8d5a-e4e73ab01e56.mp4

Is the display of certain symbols when `HITSCORE BLOOM` is OFF in HitScoreVisualizer the same as in this video?
Note that this video was taken with PlayerInfoViewer removed.

I also tried it in a minimal environment where HitScoreVisualizer and PlayerInfoViewer work, and it seems to work fine even if BLOOM is OFF at this time.
I think the cause is in another mod, but I have not been able to investigate that far.

This problem has been occurring in my environment for some time and I have been using BLOOM with it ON for a long time.

**Comment by Loloppe** [comment]
Yea it seem to be similar symbol as your video. I can try to find if it's also caused by another plugin. I switched to NalulunaFlyingScore for now since it doesn't have that issue, but I would love to go back to normal HSV.

**Comment by Loloppe** [comment]
I did a very minimal environment too and I get the exact same issue.
![image](https://user-images.githubusercontent.com/54846763/189730076-eae6e87f-c274-404c-a109-1a2f7b209729.png)
Changing the "displayMode" in HSV seem to change the symbol used by the HSV due to the bug. It's probably an issue somehow caused by TextMeshPro.
![image](https://user-images.githubusercontent.com/54846763/189732046-e3ff8bdf-5428-4243-b7b1-3a1d0a4a670d.png)

**Comment by Loloppe** [comment]
Update: I downloaded the source code, removed that following line and recompiled and everything work now:
`textMesh.font = Instantiate(Resources.FindObjectsOfTypeAll<TMP_FontAsset>().First(t => t.name == "Teko-Medium SDF Numbers Monospaced Curved"));`
From PlayerInfoView.cs, line 97.

**Comment by rynan4818** [comment]
Thank you for your detailed investigation.
Your identification of the cause is very helpful.

It seems that my investigation in my minimal environment was inadequate.
I checked again today and found this problem.

I am pretty sure that the part of the code you pointed out is the cause.

I am referring to `NowPlaying.cs` in [CustomMenuMusic](https://github.com/denpadokei/CustomMenuMusic) for this part, but
Using CustomMenuMusic with the same location removed fixed the problem in my normal environment.

I have looked into the reason for specifying this font, and it seems that it is necessary to use it to curve the text using `CurvedCanvasSettings`.

I am not sure why what I specify here would affect HitScoreVisualizer, but I would like to remove it because I hardly care if I lose the curve display.
